### ISSUE TITLE
Current curl response error json formatting error. json_decode($response, true) failed.

### ISSUE THREAD

**Issue by mantrasys** [linslin/Yii2-Curl#34]
Hello,

I have used this extension in my yii 2 application. When I had started working on using this extension the response was working fine and after json_decode() I was getting array. 

After 10 months when I updated the composer.json and project dependencies the application broke.
gettype(json_decode($response, true)) is returning NULL instead of array now, but same application on another computer with old dependencies is working fine (same code).

When using php's curl the code is working fine. Ex
----------------------------------------------------------------------------------------------
$ch = curl_init();
curl_setopt($ch,CURLOPT_URL,"http://hayageek.com");
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
$response=curl_exec($ch);
curl_close($ch);
gettype(json_decode($response)) returns array
----------------------------------------------------------------------------------------------
Attached are the old and new composer.json and composer.lock files.

Regards
Ismail.

[OldComposer.lock.txt](https://github.com/linslin/Yii2-Curl/files/400796/OldComposer.lock.txt)
[OldComposer.json.txt](https://github.com/linslin/Yii2-Curl/files/400797/OldComposer.json.txt)
[composer.lock.txt](https://github.com/linslin/Yii2-Curl/files/400798/composer.lock.txt)
[composer.json.txt](https://github.com/linslin/Yii2-Curl/files/400799/composer.json.txt)

**Comment by linslin** [comment]
Hi @mantrasys ,

which version of linslin/yii2-curl are you using? Your old composer says it was 1.0.3 in the past. There was an issue while overwriting the default options like "CURLOPT_RETURNTRANSFER" which was fixed in https://github.com/linslin/Yii2-Curl/issues/19 (v.1.0.4). 

Please provide some codes (yii2 curl) and version information. Your current aiming version is "dev-master" which is realy depending on the time of installation. 

Thanks

**Comment by linslin** [comment]
@mantrasys please provide some information, else i would close this issue soon.
